d-always:
  image: alpine:latest
  script: echo always

d-post:
  stage: .post
  image: alpine:latest
  script: echo post

d-rule:
  image: alpine:latest
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script: echo rule
